apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-testapp
  labels:
    app: nginx-testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-testapp
  template:
    metadata:
      labels:
        app: nginx-testapp
    spec:
      containers:
      - name: nginx-testapp
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      tolerations:
      - key: "DeployGroup"
        operator: "Equal"
        value: "Test"
        effect: "NoSchedule"
      nodeSelector:
        DeployGroup: Test